---
title: "Bat occupancy and relative activity"
---

Before my PhD, I collaborated with USGS, NPS, and multiple state agencies to analyze bat acoustic data collected for the North American Bat Monitoring Program (NABat).
During this time, I worked on a variety of statistical challenges in occupancy modeling including the development of model assessments and and how to account for large scale spatial patterns.

A drawback of acoustic data is that observations are sometimes classified to the wrong species.
Statistical methods to capture this observation process are required for using these data because ignoring species classification errors can lead to biased inferences about the underlying ecological processes of interest.
I also developed a novel statistical model for multivariate count data that accounts for misclassification of observations.
My approach allows observed counts *classified* to a particular species to result from a mixture of counts *originating* from other species.
Accounting for this misclassification process allows us to model the variability in probability of occurrence and activity rate across different species.
My paper discusses what auxiliary information about the classification process is required to fit this model and uses it to analyze acoustic data from bats.
This approach was the first to model misclassifications in multispecies data by directly connecting misclassified observations to the presence of other species of interest.