---
title: "Measurement errors in plant cover data"
---

Observation errors are inherent to most ecological data.
While accounting for observation errors is common in studies of wildlife species, there has been little consideration of observation errors in studies of plants.
Visual measurements of the proportion of a plot area where a plant species occurs, defined as "cover," can include both imperfect detection and measurement errors.
I developed a novel statistical model for analyzing visual measurements of plant cover that accounts for these observation errors.
My approach uses a zero-augmented beta distribution to model cover proportions and, conditional on the latent cover, accounts for both types of observation errors.
My paper shows how these observation errors can lead to biased inferences for plant cover if unaccounted for and provides study design recommendations based on a simulation study.
I also coauthored a second paper that extended this approach to analyze proportions that have been aggregated to ordinal categories.